Dev 2
AndrewErmakov/SanicCurrencyConverter pull request #1
Opened 2021-05-18 08:55 UTC by AndrewErmakov

2021-05-19 04:23 UTC, BasilNozhenkin1 requested changes
elif -

2021-05-19 04:23 UTC, BasilNozhenkin1 commented on get_amount_target_currency.py
> +    elif target_currency == 'RUB':
1. elseif наверное

2021-05-19 04:23 UTC, BasilNozhenkin1 commented on validate_json_data.py
> +async def validate_json_data(json_data):
Эта функция вызывается только внутри данного модуля?
Валидация отрабатывает?

2021-05-19 04:23 UTC, BasilNozhenkin1 commented on get_amount_target_currency.py
>          amount_target_currency = amount_original_currency * await convert_rubles_to_other_currency(original_currency)
для переменной, которая получает данные async-хронно все-таки переменную отдельную бы выделил, тем более, она используется и на строчке 8, и на 12

2021-05-19 15:16 UTC, AndrewErmakov commented on get_amount_target_currency.py
>          amount_target_currency = amount_original_currency * await convert_rubles_to_other_currency(original_currency)
Например Оо Я пока не оч догнал

2021-05-19 15:16 UTC, AndrewErmakov commented on validate_json_data.py
> +async def validate_json_data(json_data):
Уже нет)

2021-05-20 08:09 UTC, BasilNozhenkin1 requested changes

2021-05-20 08:09 UTC, BasilNozhenkin1 commented on main_app.py
> +        return json({'success': False, 'status': 421}, status=421)
Вот здесь зачем дважы статус указываешь?

2021-05-20 08:09 UTC, BasilNozhenkin1 commented on main_app.py
> +        return json({'success': False, 'status': 421}, status=421)
Аналогично

2021-05-23 13:29 UTC, merged